doctrine:
    dbal:
        connections:
            default:
                url: '%env(DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
        types:
            datetime_microseconds: Xm\SymfonyBundle\Doctrine\Types\DateTimeMicrosecondsType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

    orm:
        auto_generate_proxy_classes:  true
        enable_lazy_ghost_objects:    true
        naming_strategy:              doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping:                 true
        report_fields_where_declared: true
        validate_xml_mapping:         true
        mappings:
            App:
                type:      attribute
                is_bundle: false
                dir:       '%kernel.project_dir%/src/Entity'
                prefix:    'App\Entity'
                alias:     App
        controller_resolver:
            auto_mapping: true
        dql:
            string_functions:
                JSON_CONTAINS: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains

when@test:
    doctrine:
        dbal:
            driver:        'pdo_sqlite'
            path:          '%kernel.cache_dir%/test.db'
            # remove the url value
            url:           ~
            charset:       UTF8
            default_table_options:
                charset:   UTF8
                collation: UTF8
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir:                   '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
