overblog_graphql:
    definitions:
        schema:
            # @todo separate public?
            query:    Query
            mutation: Mutation
        mappings:
            auto_discover: false
            types:
                -   type:   yaml
                    dir:    "%kernel.project_dir%/config/graphql/types"
                    suffix: null

    security:
        enable_introspection: '%kernel.debug%'

    errors_handler:
        map_exceptions_to_parent: false
        exceptions:
            errors:
                - "Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException"

    batching_method: 'apollo'

#when@dev:
#    overblog_graphql:
#        definitions:
#            show_debug_info: true

services:
    _defaults:
        autowire:      true
        autoconfigure: true

    Xm\SymfonyBundle\Infrastructure\GraphQl\Type\:
        resource: '../../vendor/xm/symfony-bundle/Infrastructure/GraphQl/Type/*Type.php'
        tags: [ 'overblog_graphql.type' ]

    Xm\SymfonyBundle\Infrastructure\GraphQl\Query\:
        resource: '../../vendor/xm/symfony-bundle/Infrastructure/GraphQl/Query/*Query.php'
        tags: [ 'overblog_graphql.query' ]

    Xm\SymfonyBundle\EventSubscriber\GraphQlContextInitialization: ~
