prooph_event_store:
    stores:
        default:
            event_store: 'Prooph\EventStore\EventStore'

    projection_managers:
        app:
            event_store: '@Prooph\EventStore\EventStore'
            connection:  '@app.pdo_connection'
            projections:
                 auth_projection:
                    read_model: App\Projection\Auth\AuthReadModel
                    projection: App\Projection\Auth\AuthProjection
                 user_projection:
                    read_model: App\Projection\User\UserReadModel
                    projection: App\Projection\User\UserProjection
