symfonycasts_reset_password:
    request_password_repository: App\Projection\User\UserTokenFinder
    lifetime:                    172800 # 48 hours / 2 days (in seconds)
    #throttle_limit:              3600
    #enable_garbage_collection:   true
