compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs

# packages must be installed more than 10,080 minutes (7 days) ago to be considered for upgrade/install
# https://yarnpkg.com/configuration/yarnrc#npmMinimalAgeGate
npmMinimalAgeGate: 10080
