# yaml-language-server: $schema=../../vendor/symfony/routing/Loader/schema/routing.schema.json

when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
        prefix: /_error
