controllers:
    resource:
        path:      ../src/Controller/
        namespace: App\Controller
    type:     attribute

#public_default:
#    path:       /public{path}
#    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
#    defaults:
#        template: public.html.twig
#    methods: [ GET ]
#    requirements:
#        path: '.*'

admin_default:
    path:       /admin{path}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        path:     ''
        template: admin.html.twig
    methods: [ GET ]
    requirements:
        path: '.*'

user_profile:
    path:       /profile{path}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        path:     ''
        template: user.html.twig
    methods: [ GET ]
    requirements:
        path: '.*'

# activating a user when they were added by the admin
# the token is already stored in the session
user_activate:
    path:       /activate
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: user.html.twig
    methods: [ GET ]

# verifying a user's email address when they register themselves
# the token is already stored in the session
user_verify:
    path:       /verify
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: user.html.twig
    methods: [ GET ]

# the token is already stored in the session
user_reset:
    path:       /recover/reset
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: user.html.twig
    methods: [ GET ]

user_recover:
    path:       /recover{path}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: user.html.twig
    methods: [ GET ]
    requirements:
        path: '.*'

user_default:
    path:       /{path}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: user.html.twig
    methods: [ GET ]
    requirements:
        path: '.*'
